query getBook($id: String!) {
  book(id: $id) {
    id
    title
    cover
    isbn
    publishedAt
    price {
      base {
        value
        currency
      }
      tax {
        value
        currency
      }
      calculated {
        value
        currency
      }
    }
  }
}
